VERZIJA=CDX
MODUL=kad_da

SRCDOSROOT=c:\\dev\\fmk\\kadev\\data\\

PRGS=d_enter.prg d_srch.prg d_recalc.prg w_card.prg d_form.prg
CS=
ASMS=

include $(SC_BUILD_HOME_DIR)/sclib/Makefile_clipper

